//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRampAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblPaymentStatu tblPaymentStatu { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
