//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRampAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public string Barcode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Warranty { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductStatu tblProductStatu { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
